/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FileStatusRouteImport } from './routes/file-status'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QueryRouteImport } from './routes/query'

const FileStatusRoute = FileStatusRouteImport.update({
  id: '/file-status',
  path: '/file-status',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QueryRoute = QueryRouteImport.update({
  id: '/query',
  path: '/query',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/file-status': typeof FileStatusRoute
  '/query': typeof QueryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/file-status': typeof FileStatusRoute
  '/query': typeof QueryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/file-status': typeof FileStatusRoute
  '/query': typeof QueryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/file-status' | '/query'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/file-status' | '/query'
  id: '__root__' | '/' | '/file-status' | '/query'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FileStatusRoute: typeof FileStatusRoute
  QueryRoute: typeof QueryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/file-status': {
      id: '/file-status'
      path: '/file-status'
      fullPath: '/file-status'
      preLoaderRoute: typeof FileStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/query': {
      id: '/query'
      path: '/query'
      fullPath: '/query'
      preLoaderRoute: typeof QueryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FileStatusRoute: FileStatusRoute,
  QueryRoute: QueryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
